# Generated by Django 5.1.4 on 2024-12-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarena_app', '0002_alter_ulasan_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='no_hp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
